-- Textes de l'interface en français et en anglais (une ligne par clé et par langue).
-- Pour ajouter une langue : INSERT dans langues, puis les mêmes clés avec langue_id de la nouvelle langue.
-- Une clé absente dans une langue est remplacée par le français (voir GET /api/traductions).

INSERT INTO traductions (langue_id, cle, texte)
SELECT (SELECT id FROM langues WHERE code = 'fr'), cle, texte FROM (VALUES
    ('accueil.annonces_en_ligne', 'Annonces en ligne'),
    ('accueil.aucun_depot', 'Aucun'),
    ('accueil.bonjour', 'Bonjour {prenom}'),
    ('accueil.demander_depot', 'Demander un dépôt en conteneur'),
    ('accueil.dernier_depot', 'Dernier dépôt en conteneur'),
    ('accueil.erreur_chargement', 'Erreur lors du chargement du tableau de bord'),
    ('accueil.prochain_rdv', 'Prochain rendez-vous'),
    ('admin.prestations.confirmer_suppression', 'Supprimer cette prestation ?'),
    ('admin.prestations.erreur_chargement', 'Erreur lors du chargement des prestations'),
    ('admin.prestations.modifier', 'Modifier la prestation'),
    ('admin.prestations.nouvelle', 'Nouvelle prestation'),
    ('admin.prestations.titre', 'Gestion des prestations'),
    ('admin.utilisateurs.confirmer_suppression', 'Supprimer cet utilisateur ?'),
    ('admin.utilisateurs.erreur_chargement', 'Erreur lors du chargement des utilisateurs'),
    ('admin.utilisateurs.modifier', 'Modifier l''utilisateur'),
    ('admin.utilisateurs.nouveau', 'Nouvel utilisateur'),
    ('admin.utilisateurs.titre', 'Gestion des utilisateurs'),
    ('annonce.cedee', 'Cédée'),
    ('annonce.en_ligne', 'En ligne'),
    ('annonce.reservee', 'Réservée'),
    ('annonce.type.don', 'Don'),
    ('annonce.type.vente', 'Vente'),
    ('annonces.aucune', 'Aucune annonce ne correspond à votre recherche.'),
    ('annonces.aucune_mienne', 'Vous n''avez pas encore publié d''annonce.'),
    ('annonces.categorie_materiau', 'Catégorie de matériau'),
    ('annonces.confirmer_suppression', 'Supprimer cette annonce ?'),
    ('annonces.deposer', 'Déposer une annonce'),
    ('annonces.erreur_chargement', 'Erreur lors du chargement des annonces'),
    ('annonces.erreur_chargement_miennes', 'Erreur lors du chargement de vos annonces'),
    ('annonces.exemple_localisation', 'Ex. Paris'),
    ('annonces.marquer_cedee', 'Marquer comme cédée'),
    ('annonces.modifier', 'Modifier l''annonce'),
    ('annonces.nouvelle', 'Nouvelle annonce'),
    ('annonces.pas_de_description', 'Pas de description.'),
    ('annonces.publiee_le', 'Publiée le'),
    ('catalogue.aucune', 'Aucune offre publiée pour le moment.'),
    ('catalogue.erreur_chargement', 'Erreur lors du chargement du catalogue'),
    ('catalogue.inscription_confirmee', 'Inscription confirmée : « {titre} » a été ajouté à votre planning.'),
    ('catalogue.inscrit', 'Vous êtes inscrit·e'),
    ('catalogue.places_restantes', '{nombre} places restantes'),
    ('catalogue.sinscrire', 'S''inscrire'),
    ('catalogue.titre', 'Formations, ateliers et événements'),
    ('categorie.bois', 'Bois'),
    ('categorie.metal', 'Métal'),
    ('categorie.plastique', 'Plastique'),
    ('categorie.textile', 'Textile'),
    ('categorie.verre', 'Verre'),
    ('categorie_article.actualites', 'Actualités'),
    ('categorie_article.bois', 'Bois'),
    ('categorie_article.conseils', 'Conseils'),
    ('categorie_article.evenements', 'Événements'),
    ('categorie_article.upcycling', 'Upcycling'),
    ('commun.actions', 'Actions'),
    ('commun.annuler', 'Annuler'),
    ('commun.categorie', 'Catégorie'),
    ('commun.choisir_categorie', 'Sélectionner une catégorie'),
    ('commun.confirmer_suppression', 'Supprimer définitivement ?'),
    ('commun.date_debut', 'Date de début'),
    ('commun.date_fin', 'Date de fin'),
    ('commun.deconnexion', 'Déconnexion'),
    ('commun.description', 'Description'),
    ('commun.email', 'Email'),
    ('commun.enregistrer', 'Enregistrer'),
    ('commun.enregistrer_brouillon', 'Enregistrer en brouillon'),
    ('commun.erreur', 'Une erreur est survenue'),
    ('commun.gratuit', 'Gratuit'),
    ('commun.langue', 'Langue'),
    ('commun.lieu', 'Lieu'),
    ('commun.localisation', 'Localisation'),
    ('commun.modifier', 'Modifier'),
    ('commun.mot_de_passe', 'Mot de passe'),
    ('commun.mot_de_passe_min', 'Mot de passe (8 caractères minimum)'),
    ('commun.nom', 'Nom'),
    ('commun.non_precisee', 'Non précisée'),
    ('commun.precedent', 'Précédent'),
    ('commun.prenom', 'Prénom'),
    ('commun.prix', 'Prix'),
    ('commun.publier', 'Publier'),
    ('commun.rechercher', 'Rechercher'),
    ('commun.role', 'Rôle'),
    ('commun.score', 'Score'),
    ('commun.site', 'Site'),
    ('commun.soumettre_validation', 'Soumettre à validation'),
    ('commun.statut', 'Statut'),
    ('commun.suivant', 'Suivant'),
    ('commun.supprimer', 'Supprimer'),
    ('commun.tarif', 'Tarif'),
    ('commun.terminer', 'Terminer'),
    ('commun.titre', 'Titre'),
    ('commun.tous', 'Tous'),
    ('commun.toutes', 'Toutes'),
    ('commun.type', 'Type'),
    ('commun.valider', 'Valider'),
    ('compte.changer_mot_de_passe', 'Changer le mot de passe'),
    ('compte.erreur_chargement', 'Erreur lors du chargement de votre compte'),
    ('compte.langue_affichage', 'Langue d''affichage'),
    ('compte.mot_de_passe_actuel', 'Mot de passe actuel'),
    ('compte.mot_de_passe_modifie', 'Mot de passe modifié.'),
    ('compte.nouveau_mot_de_passe', 'Nouveau mot de passe (8 caractères minimum)'),
    ('compte.profil', 'Profil'),
    ('compte.profil_enregistre', 'Profil enregistré.'),
    ('compte.revoir_tutoriel', 'Revoir le tutoriel'),
    ('compte.tutoriel', 'Tutoriel'),
    ('compte.tutoriel_explication', 'Revoir la présentation des fonctionnalités de votre espace.'),
    ('connexion.creer_compte', 'Créer un compte'),
    ('connexion.espace_indisponible', 'Votre espace n''est pas encore disponible.'),
    ('connexion.se_connecter', 'Se connecter'),
    ('connexion.titre', 'Connexion'),
    ('conseils.aucun', 'Aucun conseil trouvé.'),
    ('conseils.erreur_chargement', 'Erreur lors du chargement des conseils'),
    ('conseils.mot_cle', 'Mot-clé'),
    ('conseils.publie_le', 'Publié le {date}'),
    ('depot.demande', 'Demande envoyée'),
    ('depot.deposee', 'Objet déposé'),
    ('depot.recuperee', 'Récupéré par un professionnel'),
    ('depot.validee', 'Validée'),
    ('depots.aucun', 'Aucune demande de dépôt pour le moment.'),
    ('depots.choisir_conteneur', 'Choisir un conteneur'),
    ('depots.code_barre', 'Code-barre de l''objet'),
    ('depots.code_ouverture', 'Code d''ouverture du conteneur'),
    ('depots.codes_apres_validation', 'Les codes vous seront communiqués dès que la demande sera validée.'),
    ('depots.conteneur_demande_le', 'Conteneur : {conteneur} · demandé le {date}'),
    ('depots.conteneur_souhaite', 'Conteneur souhaité'),
    ('depots.demande_envoyee', 'Demande envoyée !'),
    ('depots.demander', 'Demander un dépôt'),
    ('depots.description_objet', 'Description de l''objet'),
    ('depots.envoyer', 'Envoyer la demande'),
    ('depots.erreur_chargement', 'Erreur lors du chargement de vos dépôts'),
    ('depots.explication', 'Votre demande est validée par notre équipe, puis vous recevez un code pour ouvrir le conteneur.'),
    ('depots.placeholder_objet', 'Type d''objet, état, dimensions…'),
    ('depots.suivi', 'Suivi de mes dépôts'),
    ('depots.titre', 'Dépôts en conteneur'),
    ('forums.aucun', 'Aucun sujet pour le moment.'),
    ('forums.en_attente', 'En attente de modération'),
    ('forums.envoyer_signalement', 'Envoyer le signalement'),
    ('forums.erreur_chargement', 'Erreur lors du chargement des sujets'),
    ('forums.message', 'Message'),
    ('forums.motif', 'Motif du signalement'),
    ('forums.nouveau', 'Nouveau sujet'),
    ('forums.par', 'Par {auteur}'),
    ('forums.repondre', 'Répondre'),
    ('forums.signalement_envoye', 'Merci, le message a été signalé à l''équipe de modération.'),
    ('forums.signaler', 'Signaler'),
    ('forums.tous_les_sujets', 'Tous les sujets'),
    ('forums.votre_reponse', 'Votre réponse'),
    ('inscription.creer', 'Créer mon compte'),
    ('inscription.deja_compte', 'J''ai déjà un compte'),
    ('inscription.je_suis', 'Je suis'),
    ('inscription.particulier', 'Un particulier'),
    ('inscription.professionnel', 'Un professionnel / artisan'),
    ('jour.1', 'Lundi'),
    ('jour.2', 'Mardi'),
    ('jour.3', 'Mercredi'),
    ('jour.4', 'Jeudi'),
    ('jour.5', 'Vendredi'),
    ('jour.6', 'Samedi'),
    ('jour.7', 'Dimanche'),
    ('nav.accueil', 'Accueil'),
    ('nav.annonces', 'Annonces'),
    ('nav.articles', 'Articles'),
    ('nav.ateliers', 'Ateliers'),
    ('nav.catalogue', 'Catalogue'),
    ('nav.conseils', 'Conseils'),
    ('nav.depot_conteneur', 'Dépôt en conteneur'),
    ('nav.depots', 'Dépôts'),
    ('nav.evenements', 'Événements'),
    ('nav.forums', 'Forums'),
    ('nav.mes_annonces', 'Mes annonces'),
    ('nav.mes_projets', 'Mes projets'),
    ('nav.mon_compte', 'Mon compte'),
    ('nav.mon_planning', 'Mon planning'),
    ('nav.prestations', 'Prestations'),
    ('nav.score', 'Upcycling Score'),
    ('nav.utilisateurs', 'Utilisateurs'),
    ('offre.atelier', 'Atelier'),
    ('offre.evenement', 'Événement'),
    ('offre.formation', 'Formation'),
    ('planning.aucune_inscription', 'Vous n''êtes inscrit·e à aucune formation, aucun atelier ni aucun événement.'),
    ('planning.voir_catalogue', 'Voir le catalogue'),
    ('projets.ajouter_etape', 'Ajouter l''étape'),
    ('projets.aucun', 'Vous n''avez pas encore de projet.'),
    ('projets.aucune_etape', 'Aucune étape documentée.'),
    ('projets.confirmer_suppression', 'Supprimer ce projet et ses étapes ?'),
    ('projets.cree_le', 'Créé le {date}'),
    ('projets.creer', 'Créer le projet'),
    ('projets.erreur_chargement', 'Erreur lors du chargement de vos projets'),
    ('projets.etapes', 'Étapes de transformation'),
    ('projets.lien_photo', 'Lien vers une photo (facultatif)'),
    ('projets.ne_plus_partager', 'Ne plus partager'),
    ('projets.nouveau', 'Nouveau projet'),
    ('projets.nouvelle_etape', 'Nouvelle étape'),
    ('projets.partage', 'Partagé'),
    ('projets.partager', 'Partager avec la communauté'),
    ('projets.photo', 'photo'),
    ('projets.prive', 'Privé'),
    ('projets.supprimer', 'Supprimer le projet'),
    ('projets.titre', 'Mes projets d''upcycling'),
    ('role.1', 'Particulier'),
    ('role.2', 'Professionnel'),
    ('role.3', 'Salarié'),
    ('role.4', 'Administrateur'),
    ('salaries.articles.article', 'Article'),
    ('salaries.articles.creer', 'Créer un article'),
    ('salaries.articles.erreur_chargement', 'Erreur lors du chargement de vos articles'),
    ('salaries.articles.modifier', 'Modifier l''article'),
    ('salaries.articles.nouveau', 'Nouvel article'),
    ('salaries.articles.placeholder_texte', 'Écrivez votre article...'),
    ('salaries.articles.placeholder_titre', 'Titre de l''article'),
    ('salaries.articles.titre', 'Articles de conseils'),
    ('salaries.ateliers.creer', 'Créer un atelier'),
    ('salaries.ateliers.enregistre', 'Atelier enregistré !'),
    ('salaries.ateliers.erreur_chargement', 'Erreur lors du chargement des ateliers'),
    ('salaries.ateliers.introuvable', 'Atelier introuvable'),
    ('salaries.ateliers.modifier', 'Modifier l''atelier'),
    ('salaries.ateliers.retour', 'Retour à mes ateliers'),
    ('salaries.ateliers.titre', 'Mes ateliers'),
    ('salaries.depots.a_valider', 'À valider'),
    ('salaries.depots.aucun', 'Aucun dépôt.'),
    ('salaries.depots.code', 'Code : {code}'),
    ('salaries.depots.confirmer_depot', 'Confirmer le dépôt'),
    ('salaries.depots.deposes', 'Déposés'),
    ('salaries.depots.erreur_chargement', 'Erreur lors du chargement des dépôts'),
    ('salaries.depots.valider_demande', 'Valider la demande'),
    ('salaries.depots.valides', 'Validés'),
    ('salaries.evenements.choisir_site', 'Sélectionner un site'),
    ('salaries.evenements.creer', 'Créer un événement'),
    ('salaries.evenements.enregistre', 'Événement enregistré !'),
    ('salaries.evenements.erreur_chargement', 'Erreur lors du chargement des événements'),
    ('salaries.evenements.introuvable', 'Événement introuvable'),
    ('salaries.evenements.modifier', 'Modifier l''événement'),
    ('salaries.evenements.retour', 'Retour à mes événements'),
    ('salaries.evenements.titre', 'Mes événements'),
    ('salaries.planning.annee', 'Année'),
    ('salaries.planning.erreur_chargement', 'Erreur lors du chargement du planning'),
    ('salaries.planning.semaine', 'Semaine'),
    ('salaries.planning.semaine_du', 'Semaine du {date}'),
    ('salaries.titre_date_obligatoires', 'Le titre et la date de début sont obligatoires.'),
    ('score.actuel', 'Score actuel'),
    ('score.aucun_point', 'Aucun point gagné pour le moment.'),
    ('score.comment_gagner', 'Comment gagner des points ?'),
    ('score.erreur_chargement', 'Erreur lors du chargement du score'),
    ('score.historique', 'Historique'),
    ('score.motif.Annonce cédée', 'Annonce cédée'),
    ('score.motif.Dépôt récupéré', 'Dépôt récupéré'),
    ('score.motif.Inscription à une offre', 'Inscription à une offre'),
    ('score.points', '{nombre} points'),
    ('score.regle.annonce', 'Annonce cédée (don ou vente)'),
    ('score.regle.depot', 'Dépôt récupéré par un professionnel'),
    ('score.regle.inscription', 'Inscription à une formation, un atelier ou un événement'),
    ('score.titre', 'Mon Upcycling Score'),
    ('site.suisse', 'Suisse'),
    ('statut.annule', 'Annulé'),
    ('statut.brouillon', 'Brouillon'),
    ('statut.en_attente', 'En attente'),
    ('statut.publie', 'Publié'),
    ('statut.termine', 'Terminé'),
    ('tutoriel.1.texte', 'Voici un rapide tour des fonctionnalités de votre espace.'),
    ('tutoriel.1.titre', 'Bienvenue sur UpcycleConnect !'),
    ('tutoriel.2.texte', 'Donnez ou vendez vos objets et matériaux depuis « Mes annonces », et parcourez celles des autres membres.'),
    ('tutoriel.2.titre', 'Vos annonces'),
    ('tutoriel.3.texte', 'Pas le temps de gérer une vente ? Déposez votre objet dans un conteneur UpcycleConnect : vous recevez un code d''ouverture une fois la demande validée.'),
    ('tutoriel.3.titre', 'Le dépôt en conteneur'),
    ('tutoriel.4.texte', 'Inscrivez-vous aux formations, ateliers et événements : ils apparaissent ensuite dans « Mon planning ».'),
    ('tutoriel.4.titre', 'Le catalogue'),
    ('tutoriel.5.texte', 'Chaque dépôt, don ou inscription vous rapporte des points. Suivez leur évolution dans « Upcycling Score ».'),
    ('tutoriel.5.titre', 'Votre Upcycling Score'),
    ('tutoriel.6.texte', 'Partagez vos projets d''upcycling et échangez avec les autres membres sur les forums.'),
    ('tutoriel.6.titre', 'La communauté'),
    ('tutoriel.etape_sur', 'Étape {numero} sur {total}')
) AS t(cle, texte);

INSERT INTO traductions (langue_id, cle, texte)
SELECT (SELECT id FROM langues WHERE code = 'en'), cle, texte FROM (VALUES
    ('accueil.annonces_en_ligne', 'Online listings'),
    ('accueil.aucun_depot', 'None'),
    ('accueil.bonjour', 'Hello {prenom}'),
    ('accueil.demander_depot', 'Request a container drop-off'),
    ('accueil.dernier_depot', 'Latest container drop-off'),
    ('accueil.erreur_chargement', 'Error while loading the dashboard'),
    ('accueil.prochain_rdv', 'Next appointment'),
    ('admin.prestations.confirmer_suppression', 'Delete this service?'),
    ('admin.prestations.erreur_chargement', 'Error while loading services'),
    ('admin.prestations.modifier', 'Edit service'),
    ('admin.prestations.nouvelle', 'New service'),
    ('admin.prestations.titre', 'Service management'),
    ('admin.utilisateurs.confirmer_suppression', 'Delete this user?'),
    ('admin.utilisateurs.erreur_chargement', 'Error while loading users'),
    ('admin.utilisateurs.modifier', 'Edit user'),
    ('admin.utilisateurs.nouveau', 'New user'),
    ('admin.utilisateurs.titre', 'User management'),
    ('annonce.cedee', 'Given away / sold'),
    ('annonce.en_ligne', 'Online'),
    ('annonce.reservee', 'Reserved'),
    ('annonce.type.don', 'Donation'),
    ('annonce.type.vente', 'Sale'),
    ('annonces.aucune', 'No listing matches your search.'),
    ('annonces.aucune_mienne', 'You have not posted any listing yet.'),
    ('annonces.categorie_materiau', 'Material category'),
    ('annonces.confirmer_suppression', 'Delete this listing?'),
    ('annonces.deposer', 'Post a listing'),
    ('annonces.erreur_chargement', 'Error while loading listings'),
    ('annonces.erreur_chargement_miennes', 'Error while loading your listings'),
    ('annonces.exemple_localisation', 'e.g. Paris'),
    ('annonces.marquer_cedee', 'Mark as given away / sold'),
    ('annonces.modifier', 'Edit listing'),
    ('annonces.nouvelle', 'New listing'),
    ('annonces.pas_de_description', 'No description.'),
    ('annonces.publiee_le', 'Published on'),
    ('catalogue.aucune', 'No published offer yet.'),
    ('catalogue.erreur_chargement', 'Error while loading the catalogue'),
    ('catalogue.inscription_confirmee', 'Registration confirmed: “{titre}” has been added to your schedule.'),
    ('catalogue.inscrit', 'You are registered'),
    ('catalogue.places_restantes', '{nombre} places left'),
    ('catalogue.sinscrire', 'Sign up'),
    ('catalogue.titre', 'Training, workshops and events'),
    ('categorie.bois', 'Wood'),
    ('categorie.metal', 'Metal'),
    ('categorie.plastique', 'Plastic'),
    ('categorie.textile', 'Textile'),
    ('categorie.verre', 'Glass'),
    ('categorie_article.actualites', 'News'),
    ('categorie_article.bois', 'Wood'),
    ('categorie_article.conseils', 'Advice'),
    ('categorie_article.evenements', 'Events'),
    ('categorie_article.upcycling', 'Upcycling'),
    ('commun.actions', 'Actions'),
    ('commun.annuler', 'Cancel'),
    ('commun.categorie', 'Category'),
    ('commun.choisir_categorie', 'Select a category'),
    ('commun.confirmer_suppression', 'Delete permanently?'),
    ('commun.date_debut', 'Start date'),
    ('commun.date_fin', 'End date'),
    ('commun.deconnexion', 'Log out'),
    ('commun.description', 'Description'),
    ('commun.email', 'Email'),
    ('commun.enregistrer', 'Save'),
    ('commun.enregistrer_brouillon', 'Save as draft'),
    ('commun.erreur', 'An error occurred'),
    ('commun.gratuit', 'Free'),
    ('commun.langue', 'Language'),
    ('commun.lieu', 'Location'),
    ('commun.localisation', 'Location'),
    ('commun.modifier', 'Edit'),
    ('commun.mot_de_passe', 'Password'),
    ('commun.mot_de_passe_min', 'Password (at least 8 characters)'),
    ('commun.nom', 'Last name'),
    ('commun.non_precisee', 'Not specified'),
    ('commun.precedent', 'Previous'),
    ('commun.prenom', 'First name'),
    ('commun.prix', 'Price'),
    ('commun.publier', 'Publish'),
    ('commun.rechercher', 'Search'),
    ('commun.role', 'Role'),
    ('commun.score', 'Score'),
    ('commun.site', 'Site'),
    ('commun.soumettre_validation', 'Submit for approval'),
    ('commun.statut', 'Status'),
    ('commun.suivant', 'Next'),
    ('commun.supprimer', 'Delete'),
    ('commun.tarif', 'Price'),
    ('commun.terminer', 'Finish'),
    ('commun.titre', 'Title'),
    ('commun.tous', 'All'),
    ('commun.toutes', 'All'),
    ('commun.type', 'Type'),
    ('commun.valider', 'Approve'),
    ('compte.changer_mot_de_passe', 'Change password'),
    ('compte.erreur_chargement', 'Error while loading your account'),
    ('compte.langue_affichage', 'Display language'),
    ('compte.mot_de_passe_actuel', 'Current password'),
    ('compte.mot_de_passe_modifie', 'Password changed.'),
    ('compte.nouveau_mot_de_passe', 'New password (at least 8 characters)'),
    ('compte.profil', 'Profile'),
    ('compte.profil_enregistre', 'Profile saved.'),
    ('compte.revoir_tutoriel', 'See the tutorial again'),
    ('compte.tutoriel', 'Tutorial'),
    ('compte.tutoriel_explication', 'See the presentation of your area''s features again.'),
    ('connexion.creer_compte', 'Create an account'),
    ('connexion.espace_indisponible', 'Your area is not available yet.'),
    ('connexion.se_connecter', 'Log in'),
    ('connexion.titre', 'Log in'),
    ('conseils.aucun', 'No advice found.'),
    ('conseils.erreur_chargement', 'Error while loading advice'),
    ('conseils.mot_cle', 'Keyword'),
    ('conseils.publie_le', 'Published on {date}'),
    ('depot.demande', 'Request sent'),
    ('depot.deposee', 'Item dropped off'),
    ('depot.recuperee', 'Collected by a professional'),
    ('depot.validee', 'Approved'),
    ('depots.aucun', 'No drop-off request yet.'),
    ('depots.choisir_conteneur', 'Choose a container'),
    ('depots.code_barre', 'Item barcode'),
    ('depots.code_ouverture', 'Container opening code'),
    ('depots.codes_apres_validation', 'Your codes will be sent as soon as the request is approved.'),
    ('depots.conteneur_demande_le', 'Container: {conteneur} · requested on {date}'),
    ('depots.conteneur_souhaite', 'Preferred container'),
    ('depots.demande_envoyee', 'Request sent!'),
    ('depots.demander', 'Request a drop-off'),
    ('depots.description_objet', 'Item description'),
    ('depots.envoyer', 'Send request'),
    ('depots.erreur_chargement', 'Error while loading your drop-offs'),
    ('depots.explication', 'Our team approves your request, then you receive a code to open the container.'),
    ('depots.placeholder_objet', 'Type of item, condition, size…'),
    ('depots.suivi', 'My drop-offs'),
    ('depots.titre', 'Container drop-offs'),
    ('forums.aucun', 'No topic yet.'),
    ('forums.en_attente', 'Awaiting moderation'),
    ('forums.envoyer_signalement', 'Send report'),
    ('forums.erreur_chargement', 'Error while loading topics'),
    ('forums.message', 'Message'),
    ('forums.motif', 'Reason for reporting'),
    ('forums.nouveau', 'New topic'),
    ('forums.par', 'By {auteur}'),
    ('forums.repondre', 'Reply'),
    ('forums.signalement_envoye', 'Thank you, the message has been reported to the moderation team.'),
    ('forums.signaler', 'Report'),
    ('forums.tous_les_sujets', 'All topics'),
    ('forums.votre_reponse', 'Your reply'),
    ('inscription.creer', 'Create my account'),
    ('inscription.deja_compte', 'I already have an account'),
    ('inscription.je_suis', 'I am'),
    ('inscription.particulier', 'An individual'),
    ('inscription.professionnel', 'A professional / craftsperson'),
    ('jour.1', 'Monday'),
    ('jour.2', 'Tuesday'),
    ('jour.3', 'Wednesday'),
    ('jour.4', 'Thursday'),
    ('jour.5', 'Friday'),
    ('jour.6', 'Saturday'),
    ('jour.7', 'Sunday'),
    ('nav.accueil', 'Home'),
    ('nav.annonces', 'Listings'),
    ('nav.articles', 'Articles'),
    ('nav.ateliers', 'Workshops'),
    ('nav.catalogue', 'Catalogue'),
    ('nav.conseils', 'Advice'),
    ('nav.depot_conteneur', 'Container drop-off'),
    ('nav.depots', 'Drop-offs'),
    ('nav.evenements', 'Events'),
    ('nav.forums', 'Forums'),
    ('nav.mes_annonces', 'My listings'),
    ('nav.mes_projets', 'My projects'),
    ('nav.mon_compte', 'My account'),
    ('nav.mon_planning', 'My schedule'),
    ('nav.prestations', 'Services'),
    ('nav.score', 'Upcycling Score'),
    ('nav.utilisateurs', 'Users'),
    ('offre.atelier', 'Workshop'),
    ('offre.evenement', 'Event'),
    ('offre.formation', 'Training'),
    ('planning.aucune_inscription', 'You are not registered for any training, workshop or event.'),
    ('planning.voir_catalogue', 'See the catalogue'),
    ('projets.ajouter_etape', 'Add step'),
    ('projets.aucun', 'You don''t have any project yet.'),
    ('projets.aucune_etape', 'No step documented.'),
    ('projets.confirmer_suppression', 'Delete this project and its steps?'),
    ('projets.cree_le', 'Created on {date}'),
    ('projets.creer', 'Create project'),
    ('projets.erreur_chargement', 'Error while loading your projects'),
    ('projets.etapes', 'Transformation steps'),
    ('projets.lien_photo', 'Link to a photo (optional)'),
    ('projets.ne_plus_partager', 'Stop sharing'),
    ('projets.nouveau', 'New project'),
    ('projets.nouvelle_etape', 'New step'),
    ('projets.partage', 'Shared'),
    ('projets.partager', 'Share with the community'),
    ('projets.photo', 'photo'),
    ('projets.prive', 'Private'),
    ('projets.supprimer', 'Delete project'),
    ('projets.titre', 'My upcycling projects'),
    ('role.1', 'Individual'),
    ('role.2', 'Professional'),
    ('role.3', 'Employee'),
    ('role.4', 'Administrator'),
    ('salaries.articles.article', 'Article'),
    ('salaries.articles.creer', 'Write an article'),
    ('salaries.articles.erreur_chargement', 'Error while loading your articles'),
    ('salaries.articles.modifier', 'Edit article'),
    ('salaries.articles.nouveau', 'New article'),
    ('salaries.articles.placeholder_texte', 'Write your article...'),
    ('salaries.articles.placeholder_titre', 'Article title'),
    ('salaries.articles.titre', 'Advice articles'),
    ('salaries.ateliers.creer', 'Create a workshop'),
    ('salaries.ateliers.enregistre', 'Workshop saved!'),
    ('salaries.ateliers.erreur_chargement', 'Error while loading workshops'),
    ('salaries.ateliers.introuvable', 'Workshop not found'),
    ('salaries.ateliers.modifier', 'Edit workshop'),
    ('salaries.ateliers.retour', 'Back to my workshops'),
    ('salaries.ateliers.titre', 'My workshops'),
    ('salaries.depots.a_valider', 'To approve'),
    ('salaries.depots.aucun', 'No drop-off.'),
    ('salaries.depots.code', 'Code: {code}'),
    ('salaries.depots.confirmer_depot', 'Confirm drop-off'),
    ('salaries.depots.deposes', 'Dropped off'),
    ('salaries.depots.erreur_chargement', 'Error while loading drop-offs'),
    ('salaries.depots.valider_demande', 'Approve request'),
    ('salaries.depots.valides', 'Approved'),
    ('salaries.evenements.choisir_site', 'Select a site'),
    ('salaries.evenements.creer', 'Create an event'),
    ('salaries.evenements.enregistre', 'Event saved!'),
    ('salaries.evenements.erreur_chargement', 'Error while loading events'),
    ('salaries.evenements.introuvable', 'Event not found'),
    ('salaries.evenements.modifier', 'Edit event'),
    ('salaries.evenements.retour', 'Back to my events'),
    ('salaries.evenements.titre', 'My events'),
    ('salaries.planning.annee', 'Year'),
    ('salaries.planning.erreur_chargement', 'Error while loading the schedule'),
    ('salaries.planning.semaine', 'Week'),
    ('salaries.planning.semaine_du', 'Week of {date}'),
    ('salaries.titre_date_obligatoires', 'Title and start date are required.'),
    ('score.actuel', 'Current score'),
    ('score.aucun_point', 'No points earned yet.'),
    ('score.comment_gagner', 'How to earn points?'),
    ('score.erreur_chargement', 'Error while loading the score'),
    ('score.historique', 'History'),
    ('score.motif.Annonce cédée', 'Listing given away / sold'),
    ('score.motif.Dépôt récupéré', 'Drop-off collected'),
    ('score.motif.Inscription à une offre', 'Signed up for an offer'),
    ('score.points', '{nombre} points'),
    ('score.regle.annonce', 'Listing given away or sold'),
    ('score.regle.depot', 'Drop-off collected by a professional'),
    ('score.regle.inscription', 'Signing up for a training, workshop or event'),
    ('score.titre', 'My Upcycling Score'),
    ('site.suisse', 'Switzerland'),
    ('statut.annule', 'Cancelled'),
    ('statut.brouillon', 'Draft'),
    ('statut.en_attente', 'Pending'),
    ('statut.publie', 'Published'),
    ('statut.termine', 'Finished'),
    ('tutoriel.1.texte', 'Here is a quick tour of your area''s features.'),
    ('tutoriel.1.titre', 'Welcome to UpcycleConnect!'),
    ('tutoriel.2.texte', 'Give away or sell your items and materials from “My listings”, and browse those of other members.'),
    ('tutoriel.2.titre', 'Your listings'),
    ('tutoriel.3.texte', 'No time to handle a sale? Drop your item in an UpcycleConnect container: you receive an opening code once your request is approved.'),
    ('tutoriel.3.titre', 'Container drop-off'),
    ('tutoriel.4.texte', 'Sign up for training sessions, workshops and events: they then appear in “My schedule”.'),
    ('tutoriel.4.titre', 'The catalogue'),
    ('tutoriel.5.texte', 'Every drop-off, donation or sign-up earns you points. Track them in “Upcycling Score”.'),
    ('tutoriel.5.titre', 'Your Upcycling Score'),
    ('tutoriel.6.texte', 'Share your upcycling projects and chat with other members on the forums.'),
    ('tutoriel.6.titre', 'The community'),
    ('tutoriel.etape_sur', 'Step {numero} of {total}')
) AS t(cle, texte);


-- Ajout des clés pour l'espace Professionnels
INSERT INTO traductions (langue_id, cle, texte)
SELECT (SELECT id FROM langues WHERE code = 'fr'), cle, texte FROM (VALUES
    ('nav.pro_tableau_bord', 'Tableau de bord pro'),
    ('nav.pro_annonces', 'Catalogue des annonces'),
    ('nav.pro_conteneurs', 'Conteneurs'),
    ('nav.pro_projets', 'Projets Upcycling'),
    ('nav.pro_contrats', 'Contrats & Facturation'),
    ('nav.pro_statistiques', 'Statistiques avancées')
) AS t(cle, texte);

INSERT INTO traductions (langue_id, cle, texte)
SELECT (SELECT id FROM langues WHERE code = 'en'), cle, texte FROM (VALUES
    ('nav.pro_tableau_bord', 'Pro Dashboard'),
    ('nav.pro_annonces', 'Listings Catalog'),
    ('nav.pro_conteneurs', 'Containers'),
    ('nav.pro_projets', 'Upcycling Projects'),
    ('nav.pro_contrats', 'Contracts & Billing'),
    ('nav.pro_statistiques', 'Advanced Statistics')
) AS t(cle, texte);
